// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzqqbxbfassbfpvwfhfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6cXFieGJmYXNzYmZwdndmaGZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MTk2NjQsImV4cCI6MjA1ODQ5NTY2NH0.zPZxm8HZCqL0D7yG9JQ-iLmXkrjJGCkCMQNZ5pvp6bw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);